insert into Region (name) values ("Northeast");
insert into Region (name) values ("Southeast");


insert into Item (name, unitPrice) values ("Item1", "10.0");
insert into Item (name, unitPrice) values ("Item2", "20.0");
insert into Item (name, unitPrice) values ("Item3", "30.0");
insert into Item (name, unitPrice) values ("Item4", "40.0");
insert into Item (name, unitPrice) values ("Item5", "50.0");
insert into Item (name, unitPrice) values ("Item6", "60.0");
insert into Item (name, unitPrice) values ("Item7", "70.0");
insert into Item (name, unitPrice) values ("Item8", "80.0");
insert into Item (name, unitPrice) values ("Item9", "90.0");
insert into Item (name, unitPrice) values ("Item10", "100.0");


insert into Store (regionID, name, address) values (2, "Store1", "1 Store road");
insert into Store (regionID, name, address) values (1, "Store2", "2 Store road");
insert into Store (regionID, name, address) values (2, "Store3", "3 Store road");
insert into Store (regionID, name, address) values (1, "Store4", "4 Store road");


insert into Employee (name, type, regionId) values ("SalesRep1", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep2", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep3", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep4", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep5", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep6", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep7", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep8", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep9", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep10", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep11", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep12", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep13", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep14", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep15", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep16", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep17", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep18", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep19", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep20", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep21", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep22", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep23", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep24", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep25", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep26", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep27", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep28", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep29", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep30", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep31", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep32", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep33", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep34", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep35", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep36", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep37", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep38", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep39", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep40", 0, 1);
insert into Employee (name, type, regionId) values ("RegionalManager1", 1, 1);
insert into Employee (name, type, regionId) values ("RegionalManager2", 1, 2);
insert into Employee (name, type, regionId) values ("GeneralManager", 2, null);


insert into StoreEmployee (storeID, employeeID) values (1, 1);
insert into StoreEmployee (storeID, employeeID) values (2, 2);
insert into StoreEmployee (storeID, employeeID) values (1, 3);
insert into StoreEmployee (storeID, employeeID) values (2, 4);
insert into StoreEmployee (storeID, employeeID) values (1, 5);
insert into StoreEmployee (storeID, employeeID) values (2, 6);
insert into StoreEmployee (storeID, employeeID) values (1, 7);
insert into StoreEmployee (storeID, employeeID) values (2, 8);
insert into StoreEmployee (storeID, employeeID) values (1, 9);
insert into StoreEmployee (storeID, employeeID) values (2, 10);
insert into StoreEmployee (storeID, employeeID) values (1, 11);
insert into StoreEmployee (storeID, employeeID) values (2, 12);
insert into StoreEmployee (storeID, employeeID) values (1, 13);
insert into StoreEmployee (storeID, employeeID) values (2, 14);
insert into StoreEmployee (storeID, employeeID) values (1, 15);
insert into StoreEmployee (storeID, employeeID) values (2, 16);
insert into StoreEmployee (storeID, employeeID) values (1, 17);
insert into StoreEmployee (storeID, employeeID) values (2, 18);
insert into StoreEmployee (storeID, employeeID) values (1, 19);
insert into StoreEmployee (storeID, employeeID) values (2, 20);
insert into StoreEmployee (storeID, employeeID) values (3, 21);
insert into StoreEmployee (storeID, employeeID) values (4, 22);
insert into StoreEmployee (storeID, employeeID) values (3, 23);
insert into StoreEmployee (storeID, employeeID) values (4, 24);
insert into StoreEmployee (storeID, employeeID) values (3, 25);
insert into StoreEmployee (storeID, employeeID) values (4, 26);
insert into StoreEmployee (storeID, employeeID) values (3, 27);
insert into StoreEmployee (storeID, employeeID) values (4, 28);
insert into StoreEmployee (storeID, employeeID) values (3, 29);
insert into StoreEmployee (storeID, employeeID) values (4, 30);
insert into StoreEmployee (storeID, employeeID) values (3, 31);
insert into StoreEmployee (storeID, employeeID) values (4, 32);
insert into StoreEmployee (storeID, employeeID) values (3, 33);
insert into StoreEmployee (storeID, employeeID) values (4, 34);
insert into StoreEmployee (storeID, employeeID) values (3, 35);
insert into StoreEmployee (storeID, employeeID) values (4, 36);
insert into StoreEmployee (storeID, employeeID) values (3, 37);
insert into StoreEmployee (storeID, employeeID) values (4, 38);
insert into StoreEmployee (storeID, employeeID) values (3, 39);
insert into StoreEmployee (storeID, employeeID) values (4, 40);

insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer1", 1, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer1", 2, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer2", 3, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer3", 4, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer4", 5, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer5", 6, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer6", 7, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer7", 8, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer8", 9, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer9", 10, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer10", 11, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer11", 12, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer12", 13, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer13", 14, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer14", 15, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer15", 16, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer16", 17, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer17", 18, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer18", 19, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer19", 20, "378282246310005", "10/22", "2000-05-13 12:00:00");
insert into SalesOrder (customerName, employeeID, creditCardNumber, expirationDate, dateOfSale) values ("Customer20", 21, "378282246310005", "10/22", "2000-05-13 12:00:00");


insert into ItemOrders (orderId, itemId, quantity) values ("1", "2", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("2", "3", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("3", "4", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("4", "5", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("5", "6", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("6", "7", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("7", "8", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("8", "9", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("9", "10", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("10", "1", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("11", "2", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("12", "3", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("13", "4", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("14", "5", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("15", "6", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("16", "7", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("17", "8", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("18", "9", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("19", "10", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("20", "1", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("21", "2", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("22", "3", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("23", "4", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("24", "5", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("25", "6", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("26", "7", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("27", "8", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("28", "9", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("29", "10", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("30", "1", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("31", "2", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("32", "3", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("33", "4", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("34", "5", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("35", "6", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("36", "7", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("37", "8", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("38", "9", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("39", "10", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("40", "1", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("41", "2", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("42", "3", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("43", "4", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("44", "5", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("45", "6", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("46", "7", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("47", "8", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("48", "9", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("49", "10", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("50", "1", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("51", "2", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("52", "3", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("53", "4", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("54", "5", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("55", "6", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("56", "7", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("57", "8", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("58", "9", "2");
insert into ItemOrders (orderId, itemId, quantity) values ("59", "10", "3");
insert into ItemOrders (orderId, itemId, quantity) values ("60", "1", "1");
insert into ItemOrders (orderId, itemId, quantity) values ("61", "2", "2");