insert into Region (name) values ("Northeast");
insert into Region (name) values ("Southeast");


insert into Item (name, unitPrice) values ("Item1", "10.0");
insert into Item (name, unitPrice) values ("Item2", "20.0");
insert into Item (name, unitPrice) values ("Item3", "30.0");
insert into Item (name, unitPrice) values ("Item4", "40.0");
insert into Item (name, unitPrice) values ("Item5", "50.0");
insert into Item (name, unitPrice) values ("Item6", "60.0");
insert into Item (name, unitPrice) values ("Item7", "70.0");
insert into Item (name, unitPrice) values ("Item8", "80.0");
insert into Item (name, unitPrice) values ("Item9", "90.0");
insert into Item (name, unitPrice) values ("Item10", "100.0");


insert into Store (regionID, name, address) values (2, "Store1", "1 Store road");
insert into Store (regionID, name, address) values (1, "Store2", "2 Store road");
insert into Store (regionID, name, address) values (2, "Store3", "3 Store road");
insert into Store (regionID, name, address) values (1, "Store4", "4 Store road");


insert into Employee (name, type, regionId) values ("SalesRep1", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep2", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep3", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep4", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep5", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep6", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep7", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep8", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep9", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep10", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep11", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep12", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep13", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep14", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep15", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep16", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep17", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep18", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep19", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep20", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep21", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep22", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep23", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep24", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep25", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep26", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep27", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep28", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep29", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep30", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep31", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep32", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep33", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep34", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep35", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep36", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep37", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep38", 0, 1);
insert into Employee (name, type, regionId) values ("SalesRep39", 0, 2);
insert into Employee (name, type, regionId) values ("SalesRep40", 0, 1);
insert into Employee (name, type, regionId) values ("RegionalManager1", 1, 1);
insert into Employee (name, type, regionId) values ("RegionalManager2", 1, 2);
insert into Employee (name, type, regionId) values ("GeneralManager", 2, null);


insert into StoreEmployee (storeID, employeeID) values (1, 1);
insert into StoreEmployee (storeID, employeeID) values (2, 2);
insert into StoreEmployee (storeID, employeeID) values (1, 3);
insert into StoreEmployee (storeID, employeeID) values (2, 4);
insert into StoreEmployee (storeID, employeeID) values (1, 5);
insert into StoreEmployee (storeID, employeeID) values (2, 6);
insert into StoreEmployee (storeID, employeeID) values (1, 7);
insert into StoreEmployee (storeID, employeeID) values (2, 8);
insert into StoreEmployee (storeID, employeeID) values (1, 9);
insert into StoreEmployee (storeID, employeeID) values (2, 10);
insert into StoreEmployee (storeID, employeeID) values (1, 11);
insert into StoreEmployee (storeID, employeeID) values (2, 12);
insert into StoreEmployee (storeID, employeeID) values (1, 13);
insert into StoreEmployee (storeID, employeeID) values (2, 14);
insert into StoreEmployee (storeID, employeeID) values (1, 15);
insert into StoreEmployee (storeID, employeeID) values (2, 16);
insert into StoreEmployee (storeID, employeeID) values (1, 17);
insert into StoreEmployee (storeID, employeeID) values (2, 18);
insert into StoreEmployee (storeID, employeeID) values (1, 19);
insert into StoreEmployee (storeID, employeeID) values (2, 20);
insert into StoreEmployee (storeID, employeeID) values (3, 21);
insert into StoreEmployee (storeID, employeeID) values (4, 22);
insert into StoreEmployee (storeID, employeeID) values (3, 23);
insert into StoreEmployee (storeID, employeeID) values (4, 24);
insert into StoreEmployee (storeID, employeeID) values (3, 25);
insert into StoreEmployee (storeID, employeeID) values (4, 26);
insert into StoreEmployee (storeID, employeeID) values (3, 27);
insert into StoreEmployee (storeID, employeeID) values (4, 28);
insert into StoreEmployee (storeID, employeeID) values (3, 29);
insert into StoreEmployee (storeID, employeeID) values (4, 30);
insert into StoreEmployee (storeID, employeeID) values (3, 31);
insert into StoreEmployee (storeID, employeeID) values (4, 32);
insert into StoreEmployee (storeID, employeeID) values (3, 33);
insert into StoreEmployee (storeID, employeeID) values (4, 34);
insert into StoreEmployee (storeID, employeeID) values (3, 35);
insert into StoreEmployee (storeID, employeeID) values (4, 36);
insert into StoreEmployee (storeID, employeeID) values (3, 37);
insert into StoreEmployee (storeID, employeeID) values (4, 38);
insert into StoreEmployee (storeID, employeeID) values (3, 39);
insert into StoreEmployee (storeID, employeeID) values (4, 40);